config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :two
  resources :three
  resources :four
  resources :five
  root to: "two#index"
  resources :relationships do
    resources :conversations do
      resources :messages
    end
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :relationship, optional: true
  has_many :messages
  accepts_nested_attributes_for :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

def message_time
  created_at.strftime("%m/%d/%y at %l:%M %p")
 end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_one :conversation
  has_many :messages, through: :conversation
  belongs_to :invited_user, class_name: 'User', foreign_key: :invited_id
  belongs_to :inviting_user, class_name: 'User', foreign_key: :inviting_id
  accepts_nested_attributes_for :conversation

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Paperclip Shit
  has_attached_file :avatar, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :posts, dependent: :destroy

  # User/Relationship Association Logic
  has_many :sent_invites, class_name: "Relationship", foreign_key: :inviting_id
  has_many :received_invites, class_name: "Relationship", foreign_key: :invited_id
  has_many :invited_users, through: :sent_invites, source: :invited_user
  has_many :inviting_users, through: :received_invites, source: :inviting_user
  has_many :conversations, through: :relationships
  has_many :messages, through: :conversations

  #Data objects for User Registration/Edit dropdown menus
  LOCATIONS = ['Philadelphia', 'New York', 'Washington D.C', 'Boston', 'Chicago', 'Austin', 'Dallas', 'San Francisco', 'Los Angeles', 'San Diego', 'Seattle', 'Portland', 'Denver']
  PROFESSIONS = ['Tech', 'Hospitality', 'Science', 'Engineering', 'Medical', 'Event Organization']
  AGES = [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
     31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
      41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
  61, 62, 63, 64, 65, 66, 67, 68, 69, 70 ]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:given_name, :family_name, :age, :location, :profession, :gender, :bio_short, :bio_long, :avatar])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :remember_me])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def show
    @relationship = Relationship.find(params[:relationship_id])
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages
  if @messages.length > 10
   @over_ten = true
   @messages = @messages[-10..-1]
  end
  if params[:m]
   @over_ten = false
   @messages = @conversation.messages
  end
 if @messages.last
  if @messages.last.user_id != current_user.id
   @messages.last.read = true;
  end
  end
  @message = @conversation.messages.new

end

def new
 @message = @conversation.messages.new
end

  def create
    @relationship = Relationship.find(params[:relationship_id])
    @conversation = Conversation.create!(:relationship_id => @relationship)
    redirect_to relationship_conversation_path(@relationship.id, @conversation.id)
  end

end

private


def conversation_params
 params.require(:conversation).permit(:body, :relationship_id, :conversation_id, :id)
end

app/controllers/five_controller.rb
class FiveController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @session = user_session
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
     @conversation = Conversation.find(params[:conversation_id])
    end

  def index

  end

def new
 @message = @conversation.messages.new
end

def create
@conversation = Conversation.find(params[:conversation_id])
 @message = @conversation.messages.create(message_params)
  redirect_to relationship_conversation_path(id: @conversation.id)

end
end

 def message_params
  params.require(:message).permit(:body, :user_id, :conversation_id, :id, :created_at, :updated_at)
 end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!

  def index
    @sent_invites = current_user.sent_invites
    @received_invites = current_user.received_invites
  end

  def create
    @invited_user = User.find(params[:relationship][:invited_id])

    @relationship = current_user.sent_invites.build(invited_id: @invited_user.id)

    if @relationship.save
        flash[:success] = "Successfully invited"
        # Render call here? Matchmaker Method call?
    else
        flash[:danger] = "Unsuccessful"
    end
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    if @relationship.inviting_user == current_user
      @relationship.destroy
      flash[:success] = "Removed relationship"
    end
end



end

app/controllers/two_controller.rb
class TwoController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
    @relationships = Relationship.all
    @session = user_session
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/five_helper.rb
module FiveHelper
end

app/helpers/four_helper.rb
module FourHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/one_helper.rb
module OneHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/six_helper.rb
module SixHelper
end

app/helpers/three_helper.rb
module ThreeHelper
end

app/helpers/two_helper.rb
module TwoHelper
end

app/views/conversations/show.html.erb
<div class="ui segment">
 <% @messages.each do |m| %>
  <% if m.body %>
   <% user = User.find(m.user_id) %>
   <div class="item">
    <div class="content">
     <div class="header">
       <strong>
         <%= user.given_name %>
       </strong>

          </div>
      <div class="list">
       <div class="item">
        <i class="right triangle icon"></i>
         <%= m.body %>
      </div>
    </div>
   </div>
 </div>
 <% end %>
<% end %>
</div>




<%= form_for ([@relationship, @conversation, @message]) do |f| %>
<%= f.text_area :body %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :conversation_id, value: @conversation.id %>
<%= content_tag :div, class: 'yes-btn' do -%>
<%= f.submit 'Accept', class: 'btn btn-primary' %>
<% end -%>
<% end %>

app/views/relationships/index.html.erb
<%= link_to "Back to Matching", root_path %>
<%= link_to "Edit Profile", edit_user_registration_path %>

<div class="convo_match_queue">
  <h3>Match Queue</h3>

  <div class="convo_pending_match_thumbs">
    <% # Render stuff here %>
    <% #=image_tag @inviter.avatar.url(:thumb) %>
  </div>

  <h3>Conversations</h3>
</div>

<div class="convo_list">
  <% if @received_invites.any? %>
    <% @received_invites.each do |i| %>
    <% @id = i.inviting_id %>
    <% @inviter = User.find_by_id(@id) %>
    <%= image_tag @inviter.avatar.url(:thumb) %>
    <% @relationship = Relationship.find_by_inviting_id_and_invited_id(@inviter.id, current_user.id ) %>
    <%= link_to @inviter.given_name, relationship_conversations_path(id: @inviter.id, relationship_id: @relationship.id), method: 'post'%>
    <% #= convo.last %>
    <% end %>
  <% end %>

  <% if @sent_invites.any? %>
    <% @sent_invites.each do |i| %>
    <% @id2 = i.invited_id %>
    <% @invitee = User.find_by_id(@id2) %>
    <%= image_tag @invitee.avatar.url(:thumb) %>
    <% @relationship = Relationship.find_by_inviting_id_and_invited_id(current_user.id, @invitee.id ) %>
    <%= link_to @invitee.given_name, relationship_conversations_path(id: @invitee.id, relationship_id: @relationship.id), method: 'post'%>
    <% #= convo.last %>
    <% end %>
  <% end %>
</div>