config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :two
  resources :three
  resources :four
  resources :five
  root to: "two#index"
  resources :relationships do
    resources :conversations do
      resources :messages
    end
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :relationship, optional: true
  has_many :messages
  accepts_nested_attributes_for :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

def message_time
  created_at.strftime("%m/%d/%y at %l:%M %p")
 end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_one :conversation
  has_many :messages, through: :conversation
  belongs_to :invited_user, class_name: 'User', foreign_key: :invited_id
  belongs_to :inviting_user, class_name: 'User', foreign_key: :inviting_id
  accepts_nested_attributes_for :conversation

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Paperclip Shit
  has_attached_file :avatar, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :posts, dependent: :destroy

  # User/Relationship Association Logic
  has_many :sent_invites, class_name: "Relationship", foreign_key: :inviting_id
  has_many :received_invites, class_name: "Relationship", foreign_key: :invited_id
  has_many :invited_users, through: :sent_invites, source: :invited_user
  has_many :inviting_users, through: :received_invites, source: :inviting_user
  has_many :conversations, through: :relationships
  has_many :messages, through: :conversations

  #Data objects for User Registration/Edit dropdown menus
  LOCATIONS = ['Philadelphia', 'New York', 'Washington D.C', 'Boston', 'Chicago', 'Austin', 'Dallas', 'San Francisco', 'Los Angeles', 'San Diego', 'Seattle', 'Portland', 'Denver']
  PROFESSIONS = ['Tech', 'Hospitality', 'Science', 'Engineering', 'Medical', 'Event Organization']
  AGES = [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
     31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
      41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
  61, 62, 63, 64, 65, 66, 67, 68, 69, 70 ]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:given_name, :family_name, :age, :location, :profession, :gender, :bio_short, :bio_long, :avatar])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :remember_me])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def show
    @relationship = Relationship.find(params[:relationship_id])
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages
  if @messages.length > 10
   @over_ten = true
   @messages = @messages[-10..-1]
  end
  if params[:m]
   @over_ten = false
   @messages = @conversation.messages
  end
 if @messages.last
  if @messages.last.user_id != current_user.id
   @messages.last.read = true;
  end
  end
  @message = @conversation.messages.new

end

def new
 @message = @conversation.messages.new
end

  def create
    @relationship = Relationship.find(params[:relationship_id])
    @conversation = Conversation.create!(:relationship_id => @relationship)
    redirect_to relationship_conversation_path(@relationship.id, @conversation.id)
  end

end

private


def conversation_params
 params.require(:conversation).permit(:body, :relationship_id, :conversation_id, :id)
end

app/controllers/five_controller.rb
class FiveController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @session = user_session
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
     @conversation = Conversation.find(params[:conversation_id])
    end

  def index

  end

def new
 @message = @conversation.messages.new
end

def create
@conversation = Conversation.find(params[:conversation_id])
 @message = @conversation.messages.create(message_params)
  redirect_to relationship_conversation_path(id: @conversation.id)

end
end

 def message_params
  params.require(:message).permit(:body, :user_id, :conversation_id, :id, :created_at, :updated_at)
 end

app/controllers/two_controller.rb
class TwoController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
    @relationships = Relationship.all
    @session = user_session
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/five_helper.rb
module FiveHelper
end

app/helpers/four_helper.rb
module FourHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/one_helper.rb
module OneHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/six_helper.rb
module SixHelper
end

app/helpers/three_helper.rb
module ThreeHelper
end

app/helpers/two_helper.rb
module TwoHelper
end

app/views/five/show.html.erb
<h3><%= @user.given_name %></h3>
<%= link_to "Back to Your Conversation", convo_view_path %>
<% if current_user %>
  <% @relationship = current_user.sent_invites.where(invited_id: @user.id).first %>
  <%= link_to "Unmatch", @relationship, method: :delete %>
  <% end %>
<% end %>

app/views/two/_match_card.html.erb
<div id='match-card'>
  <% puts user.given_name %>
  <%= image_tag user.avatar.url(:medium) %>

  <%= content_tag :div, class: 'match-card-user-info' do -%>
  <%= content_tag :h3 do -%>
  <%= user.given_name %>
<% end -%>
<%= content_tag :h5 do -%>
<%= user.profession %>
<% end -%>
<%= content_tag :h5 do -%>
<%= user.bio_short %>
<% end -%>
<% end -%>

<%= form_for :relationship, url: relationships_path, html: { method: :post }, remote: true do |f| %>
<%= f.hidden_field :invited_id, value: user.id %>
<%= content_tag :div, class: 'yes-btn' do -%>
<%= f.submit 'Accept', class: 'btn btn-primary' %>
<% end -%>
<% end %>
</div>

app/views/two/index.html.erb
<%= link_to "Your Conversations", relationships_path %>
<%= link_to "Edit Profile", edit_user_registration_path %>

<% x =  false %>
  <% while x == false %>
    <% @users.each do |u| %>
    <%= puts current_user.given_name %>
      <% @relationship = current_user.sent_invites.where(invited_id: u.id) %>
        <% if @relationship %>
          <% puts u.given_name %>
            <%= render partial: "match_card", locals: {user: u} %>
          <% end %>
        <% end %>
        <% x = true %>
        <% end %>

        <button type="button," name='Reject'>

app/views/two/matcher.js.erb
$('#match-card').html("<%= escape_javascript(render :partial => 'match_card' %>");